sudo: required
language: python
python:
  - '3.6'
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11  
addons:
  postgresql: "11.2"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE projects_fair_db;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: oARTuiOxqLFzf70gxEyYoaPhPtO6LJYjDp9Ab2ONZCKXw/U6exX+IhfLcRg5nySyb1gABhR0eaQYyN9c2Du/fv7BjBgQQNgOYSFOdxwn/Mf19srl596/uaPciwljWn300Dy3Rfl8nQJmxaZ4dPR4PPE+Ldlf7zOyAwD/iPPl6g6VKCs0fYOMuXBwC4WShr9dorAHMFyfHFgjNaP8fK0koUVF9mM1fBw3ylbV9ZATqNHhEN3OBYIf6Fq5OGhF1ud8Le/uHTSGdLOwNPfnf3F86kYcgGlb1AfQLyAEREnpcGq+DIc196ZYFiBW/CdLLnf4DqYvUrOaUt4CNnMQwJIFgnHpNdBa2vO0QVtcazBVk6uyYALzXyjCPtqioNrdlTifSw6/Wkm2Wv6+CcpUsjTQcF1eEmXsJF34Xe3Qp8zdDNkADkhDDGv9Vuoelfl/ZB7TGaaPUim1IBItlhlHePToqAgw+ZnLiZaedyoA3CjT9jyDz1TSIFkUOhVZ/LtTSuluAm23mkxC+WAUxZQHwdayypSz2hRvtQ9GSUIg+8c9jMau/2K5DwDf9cXtkLMazQOzipil8ewhnJJrBNu5dYAWWy8htazpnsml2KQDhVHsOIqrKSF+8v2OAhSeiFDyuYVfMClGhIunixPULTlZNkpk6aNRGqGm63jTVwO2hubVTZg=
  app: projects-fair
  on:
    repo: nikita03565/projects_fair
  run: 
    - "python manage.py makemigrations"
    - "python manage.py migrate"
